### ISSUE TITLE
Image Not Valid Size for CoreML

### ISSUE THREAD

**Issue by interactivetech** [artemnovichkov/iOS-11-by-Examples#10]
I try to run the app and I get this error

{Error Domain=com.apple.CoreML Code=1 "Image is not valid width 299, instead is 449" UserInfo={NSLocalizedDescription=Image is not valid width 299, instead is 449}}}

I see in the UIImage+Processing.swift that you resize the image to 149.5 rather than the model input size, which is 299. I am testing on an iPhone6SPlus, so I am not sure if screen size is an issue.

Any help or advice on how to trouble shoot would be great!

**Comment by interactivetech** [comment]
I noticed that 149.5 is half of 299, so I am thinking you are hardcoding the resizing so the image gets to 299. The factor off the iphone6s is to whatever phone you were testing was 449/299  = 1.5016722408, so I resized by:

width: 149.5/1.5016722408, height: 149.5/1.5016722408, and it worked for me.

Is there a more robust way to resize the image so you get the exact dimensions you need?

**Comment by artemnovichkov** [comment]
I guess it depends on screen size. Can you fix it and make a pull request?

**Comment by glennposadas** [comment]
@interactivetech , can you share your solution? I'm trying to crop the captured image by 299, 299. I know I'm doing it wrong.

**Comment by artemnovichkov** [comment]
Hi, @interactivetech and @glennposadas! I have updated logic of converting images to pixel buffers. Can you check it on your devices?
