### ISSUE TITLE
Unavailable issues

### ISSUE THREAD

**Issue by WillRRRR** [artemnovichkov/iOS-11-by-Examples#11]
An Application Group with Identifier 'group.com.artemnovichkov.iOS-11-by-Examples' is not available. Please enter a different string. <img width="509" alt="screen shot 2017-07-26 at 10 35 05 am" src="https://user-images.githubusercontent.com/30376565/28629841-2b2c19e6-71ee-11e7-84ed-10e7c88bc41d.png">

**Comment by artemnovichkov** [comment]
I use app group for sharing data saved in `UserDefaults` between main app and MessagesFilter extension. You can change app groups in Capabilities tab in iOS-11-by-Examples and MessagesFilter target.

**Comment by artemnovichkov** [comment]
Have I helped you?
