### ISSUE TITLE
Team failed

### ISSUE THREAD

**Issue by WillRRRR** [artemnovichkov/iOS-11-by-Examples#12]
<img width="1397" alt="screen shot 2017-07-26 at 11 00 55 am" src="https://user-images.githubusercontent.com/30376565/28631103-bcd81626-71f1-11e7-8a4c-61013576c5ff.png">

**Comment by artemnovichkov** [comment]
You must add code signing for MessageFilter extension as well. Thank you for your issues, I'll update README with notes about app groups and code signing.
