### ISSUE TITLE
Swift Code Error

### ISSUE THREAD

**Issue by WillRRRR** [artemnovichkov/iOS-11-by-Examples#13]
<img width="1400" alt="screen shot 2017-07-26 at 11 20 53 am" src="https://user-images.githubusercontent.com/30376565/28631960-964c6dce-71f4-11e7-980d-4513b1014527.png">
<img width="1403" alt="screen shot 2017-07-26 at 11 20 59 am" src="https://user-images.githubusercontent.com/30376565/28631961-96618434-71f4-11e7-8ec1-ac06aee99963.png">

**Comment by artemnovichkov** [comment]
The second warning is normal, it doesn't break something. About the first - which version of Xcode do you use?

**Comment by WillRRRR** [comment]
Xcode 9 Beta 4

**Comment by artemnovichkov** [comment]
I have fixed it. Can you check it?

**Comment by WillRRRR** [comment]
working it
