### ISSUE TITLE
Miss some features from App

### ISSUE THREAD

**Issue by WillRRRR** [artemnovichkov/iOS-11-by-Examples#14]
including:
+Core NFC
+DeviceCheck

![img_1208](https://user-images.githubusercontent.com/30376565/28638499-a7ca231e-720a-11e7-9add-25a9d24c68a0.PNG)

**Comment by WillRRRR** [comment]
Core NFC and DeviceCheck colored red in Xcode 9 Beta 4 that's can't use in iOS Device!

<img width="196" alt="screen shot 2017-07-26 at 2 15 16 pm" src="https://user-images.githubusercontent.com/30376565/28639177-e256e15a-720c-11e7-92d4-b150ec6919f1.png">

**Comment by artemnovichkov** [comment]
I moved it to separate targets. Please check notes in README for there examples.
