### ISSUE TITLE
Use of unresolved identifier 'ARWorldTrackingConfiguration'

### ISSUE THREAD

**Issue by mobyIsMe** [artemnovichkov/iOS-11-by-Examples#17]
Swift Compiler Error：Use of unresolved identifier 'ARWorldTrackingConfiguration'
location：
![image](https://user-images.githubusercontent.com/9191594/29158307-15b07850-7ddd-11e7-935b-eb9f985c02e5.png)

IDE：Xcode9.0 beta3
thanks.

**Comment by artemnovichkov** [comment]
Hi! Please update your Xcode to beta 5 or just fix the error with autocompletion.
