### ISSUE TITLE
Screen capture example

### ISSUE THREAD

**Issue by d3mac123** [artemnovichkov/iOS-11-by-Examples#18]
Hi! Do you have any screen capture example? I used to use this code (mixed with some Javascript/Nativescript) but, for some reason, it is not working anymore after updating to iOS11. I belive this is related to the new behavior of a screenshot (which now shows the captured image for a few seconds, before saving or opening it for editing):

```
UIGraphicsBeginImageContextWithOptions(view.ios.frame.size, false, 0);
view.ios.drawViewHierarchyInRectAfterScreenUpdates(CGRectMake(0, 0, view.ios.frame.size.width, view.ios.frame.size.height), true);
var imageFromCurrentImageContext = UIGraphicsGetImageFromCurrentImageContext();
UIGraphicsEndImageContext();
return imageSource.fromData(UIImagePNGRepresentation(imageFromCurrentImageContext));
```

**Comment by artemnovichkov** [comment]
Hi, @d3mac123! As I understand, you want to take a screenshot of entire screen, right? I didn't add it to my examples because there are no changes in API related to this function, as I know.

**Comment by d3mac123** [comment]
Thanks @artemnovichkov. Really weird that the code stopped to work after the update... 😕
