### ISSUE TITLE
Error code in MessageFilterExtension.swift

### ISSUE THREAD

**Issue by cairano** [artemnovichkov/iOS-11-by-Examples#20]
Hi there!

There is an error in line 48 of the `MessageFilterExtension.swift` file... For some reason that I do not figure out yet, I can't submit a pull request, so here is the line to fix:

`let messageBody = queryRequest.messageBody ?? "No body"`

Thanks for sharing this code, help me a lot!! ;-)

**Comment by artemnovichkov** [comment]
HI, @cairano! Sorry, I missed the issue. what's your problem? And which Xcode version do you use?
