### ISSUE TITLE
Do anyone has the Sample Code for "Handling 3D Interaction and UI Controls in Augmented Reality"

### ISSUE THREAD

**Issue by omarojo** [artemnovichkov/iOS-11-by-Examples#22]
Apple published the "Handling 3D Interaction and UI Controls in Augmented Reality" sample code.
but this is for BETA iOS 11.3.

Do anyone has the previous 11.2 version ? I dont want to develop for 11.3 I want to develop to current latest public iOS version.

https://developer.apple.com/documentation/arkit/handling_3d_interaction_and_ui_controls_in_augmented_reality

**Comment by artemnovichkov** [comment]
Hi, @omarojo! unfortunately, it's available only for iOS 11.3+ projects.
