### ISSUE TITLE
Why a paid apple developer account is must?

### ISSUE THREAD

**Issue by hemangshah** [artemnovichkov/iOS-11-by-Examples#4]
To run this project, we should provide our own Apple Developer paid Account. Now, this should not be a constraint. I am not having an Apple account, what should I do run it? Generally, I should able to install an app in my iPhone with my Apple ID which is not linked to paid membership.

**Comment by artemnovichkov** [comment]
Hi, @hemangshah! Your question related to Capabilities. At least you should enable NFC Tag Reading for NFC example. I thought about it and maybe I will move this example to separate target. Anyway, you can deploy to a device without an Apple Developer Account, here is a [good article](http://blog.ionic.io/deploying-to-a-device-without-an-apple-developer-account/).

**Comment by hemangshah** [comment]
@artemnovichkov, very quick reply! 👍 Here I have to clear you, I am able to install apps without an Apple Developer account. But right now, the issue is something with the group. How do you I set up that group? Or should I remove a target to fix this?

**Comment by artemnovichkov** [comment]
What's the group? Don't remove the target, try to disable NFC Tag Reading in Capabilities and comment NFC example. Please let me know if it helps you.

**Comment by hemangshah** [comment]
@artemnovichkov, yes this should help, but I have removed the problem target, some entries from the plist, and turned off a capability, this worked! 👍 Nice work! I have few questions with the CoreML. Should I open a separate issue?

**Comment by artemnovichkov** [comment]
Nice! Yes, open another issue, please. Can I close this issue?

**Comment by hemangshah** [comment]
Thank you!! 👍

**Comment by hemangshah** [comment]
**If you don't have an Apple account, you can follow these steps to run it with your AppleID.**

1. Turned off App Group in both targets. a) iOS11-by-Example b) MessagesFilter
2. Remove "nfc" from key "Required device capabilities" inside the plist file.
3. Select your AppleID to sign and run!
4. It should work well. No need to do any other settings.

**Comment by artemnovichkov** [comment]
@hemangshah, thank you! Maybe I'll add it to README
