### ISSUE TITLE
How CoreML is working in the sample?

### ISSUE THREAD

**Issue by hemangshah** [artemnovichkov/iOS-11-by-Examples#5]
I am seeing "Inceptionv3.mlmodel" file inside the "CoreML" group. I am sure that the answers are coming from that 91mb mlmodel file. 

**Few questions:**

1. Where did you get this file?
2. Is this the dependency for this task? I mean, if we don't have this file, we couldn't do this?
3. Why we need CoreML framework to work with this file?

P.S. Here this file means, mlmodel file.

**Comment by artemnovichkov** [comment]
Step by step:
1. Apple provides several popular, open source models that are already in .mlmodel format, you can find it [here](https://developer.apple.com/machine-learning/). There is Core ML Tools, a python package, converting models from machine learning toolboxes into the Core ML format (more information [here](https://pypi.python.org/pypi/coremltools))
2. Yes, this file contains trained ML model, and you can make no predictions without the model.
3. You can use Vision framework as well. It works with internal system and custom app models.

**Comment by hemangshah** [comment]
Thanks! 💯

**Comment by hemangshah** [comment]
So how CoreML framework would work with this mlmodels?

**Comment by artemnovichkov** [comment]
Xcode generates special class with input and output format. You can see it if you click on .mlmodel in Xcode:
![screen shot 2017-06-28 at 16 10 12](https://user-images.githubusercontent.com/5051597/27632026-50b02dac-5c1c-11e7-8fa9-ddd0f9b0003d.png)
All you need to do in the app is initiate model class and call `prediction(input:)` function.

**Comment by hemangshah** [comment]
That class has only 70 lines of code and the thing is I am not getting how exactly a CoreML work with that mlmodel to understand an object?

**Comment by artemnovichkov** [comment]
Do you want to now how trained model predicts any output or how Core ML use .mlmodel file?

**Comment by hemangshah** [comment]
How CoreML use .mlmodel file? Yes, I can see the **generated** source code, but what is the internal work of CoreML framework?

**Comment by artemnovichkov** [comment]
I guess, [Core ML in depth](https://developer.apple.com/videos/play/wwdc2017/710/) WWDC session will help you 🚀
