### ISSUE TITLE
New Core Image Filters

### ISSUE THREAD

**Issue by hipwelljo** [artemnovichkov/iOS-11-by-Examples#9]
Could you add examples of the new Core Image filters?
`CITextImageGenerator`, `CIColorCurves`, `CILabDeltaE`, `CIBokehBlur`, `CIMinMaxRed` and `CIBicubicScaleTransform`.

**Comment by artemnovichkov** [comment]
Hi, @hipwelljo! Why not? I have not worked with Core Image filters at all. I let you know about implementation.

**Comment by artemnovichkov** [comment]
Check [ci-filters](https://github.com/artemnovichkov/iOS-11-by-Examples/tree/ci-filters) branch please. I have played a little with new filters. There is no information about filter settings in docs, but you can play with it and create a pull request.
